"use client";
import Link from "next/link";
import { use, useEffect, useState } from "react";
import { usePortal } from "@/lib/usePortal";

export default function AdminTherapistDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const { data, loading: authLoading } = usePortal("admin");
  const [record, setRecord] = useState<any>(null); const [form, setForm] = useState<any>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [invitation, setInvitation] = useState<any>(null); const [resending, setResending] = useState(false);
  function load() { if (!data) return; fetch(`/api/admin/therapists/${id}`).then(r => r.json()).then(d => { setRecord(d); if (d.therapist) setForm({ fullName: d.therapist.fullName, email: d.therapist.email, phone: d.therapist.phone || "", professionalTitle: d.therapist.professionalTitle || "", specialty: d.therapist.specialty || "", bio: d.therapist.bio || "", active: d.therapist.active }); setLoading(false); }).catch(() => setLoading(false)); }
  useEffect(() => { load(); }, [data, id]);
  async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); const r = await fetch(`/api/admin/therapists/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); setSaving(false); if (!r.ok) setError(d.error || "Unable to save."); else load(); }
  async function resendInvitation() { setResending(true); setError(""); const r = await fetch(`/api/admin/users/${record.therapist.userId}/invitation`, { method: "POST" }); const d = await r.json(); setResending(false); if (!r.ok) { setError(d.error || "Unable to resend invitation."); return; } setInvitation(d.invitation); }
  if (authLoading || loading) return <div className="p-8 text-[#8a7e6a]">Loading…</div>;
  if (!record?.therapist || !form) return <div className="p-8 text-red-600">Therapist not found.</div>;
  return <div className="px-6 md:px-10 py-8 md:py-12 max-w-5xl">
    <Link href="/admin/therapists" className="text-sm text-[#1a3325] hover:underline">← Back to Therapists</Link><h1 className="font-serif text-2xl font-medium text-[#1a3325] mt-5 mb-8">Manage {record.therapist.fullName}</h1>
    <form onSubmit={save} className="bg-white border border-[#e5e0d6] rounded-xl p-6 grid md:grid-cols-2 gap-4 mb-8">
      <div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Name</label><input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} className="w-full px-4 py-3 border rounded-lg border-[#ddd9cf]" /></div>
      <div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Email</label><input value={form.email} type="email" onChange={e=>setForm({...form,email:e.target.value})} className="w-full px-4 py-3 border rounded-lg border-[#ddd9cf]" /></div>
      <div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="w-full px-4 py-3 border rounded-lg border-[#ddd9cf]" /></div>
      <div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Professional Title</label><input value={form.professionalTitle} onChange={e=>setForm({...form,professionalTitle:e.target.value})} className="w-full px-4 py-3 border rounded-lg border-[#ddd9cf]" /></div>
      <div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Specialty</label><input value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})} className="w-full px-4 py-3 border rounded-lg border-[#ddd9cf]" /></div>
      <label className="flex items-center gap-2 text-sm text-[#5a554d] pt-7"><input type="checkbox" disabled={!record.therapist.verified} checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})} /> Active for new bookings {!record.therapist.verified && <span className="text-xs text-[#8a7e6a]">(activation required)</span>}</label>
      <div className="md:col-span-2"><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Biography</label><textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} className="w-full px-4 py-3 border rounded-lg border-[#ddd9cf] h-28" /></div>
      {error&&<p className="md:col-span-2 text-sm text-red-600">{error}</p>}
      <div className="md:col-span-2 flex flex-wrap gap-3"><button disabled={saving} className="bg-[#1a3325] text-white font-bold py-2.5 px-5 rounded-md disabled:opacity-50">{saving?"Saving…":"Save Changes"}</button>{!record.therapist.active&&!record.therapist.verified&&<button type="button" onClick={resendInvitation} disabled={resending} className="border border-[#1a3325] text-[#1a3325] font-bold py-2.5 px-5 rounded-md disabled:opacity-50">{resending?"Creating…":"Resend Invitation"}</button>}</div>
    </form>
    {invitation && <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 mb-8 text-sm"><p className="font-medium text-[#1a3325]">A fresh activation invitation was created. Email delivery is not configured.</p>{invitation.activationUrl?<a href={invitation.activationUrl} target="_blank" rel="noreferrer" className="block mt-2 break-all font-bold text-[#1a3325] underline">Open development activation link</a>:<p className="mt-2 text-[#8a7e6a]">Activation URLs are available only in explicit development/demo mode.</p>}</div>}
    <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border border-[#e5e0d6] rounded-xl p-5"><h2 className="font-medium text-[#1a3325] mb-3">Assigned Clients ({record.therapist.clientCount})</h2>{record.clients.length?<div className="space-y-2 text-sm">{record.clients.map((c:any)=><div key={c.id} className="border-b border-[#eceae6] pb-2"><p>{c.fullName}</p><p className="text-[#8a7e6a]">{c.email}</p></div>)}</div>:<p className="text-sm text-[#5a554d]">No assigned clients.</p>}</section><section className="bg-white border border-[#e5e0d6] rounded-xl p-5"><h2 className="font-medium text-[#1a3325] mb-3">Upcoming Appointments</h2>{record.upcomingAppointments.length?<div className="space-y-2 text-sm">{record.upcomingAppointments.map((a:any)=><div key={a.id} className="border-b border-[#eceae6] pb-2"><p>{a.date} · {a.startTime}–{a.endTime}</p><p className="text-[#8a7e6a]">{a.clientName} · {a.serviceName || "Session"}</p></div>)}</div>:<p className="text-sm text-[#5a554d]">No upcoming appointments.</p>}</section></div>
  </div>;
}
