"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { usePortal } from "@/lib/usePortal";

const EMPTY_FORM = { fullName: "", email: "", phone: "", professionalTitle: "", specialty: "", bio: "" };

export default function AdminTherapists() {
  const { data, loading: authLoading } = usePortal("admin");
  const [therapists, setTherapists] = useState<any[]>([]); const [search, setSearch] = useState(""); const [active, setActive] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true);
  const [showAdd, setShowAdd] = useState(false); const [form, setForm] = useState(EMPTY_FORM); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState(""); const [invitation, setInvitation] = useState<any>(null);
  const limit = 20;
  function load() { if (!data) return; const p = new URLSearchParams({ page: String(page), limit: String(limit) }); if (search) p.set("search", search); if (active) p.set("active", active); fetch(`/api/admin/therapists?${p}`).then(r => r.json()).then(d => { setTherapists(d.therapists || []); setTotal(d.total || 0); setLoading(false); }).catch(() => setLoading(false)); }
  useEffect(() => { load(); }, [data, search, active, page]);
  async function create(e: React.FormEvent) { e.preventDefault(); setSaving(true); setFormError(""); const r = await fetch("/api/admin/therapists", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); setSaving(false); if (!r.ok) { setFormError(d.error || "Unable to create therapist."); return; } setShowAdd(false); setForm(EMPTY_FORM); setInvitation(d.invitation || null); load(); }
  if (authLoading) return <div className="p-8 text-[#8a7e6a]">Loading…</div>;
  const pages = Math.max(1, Math.ceil(total / limit));
  return <div className="px-6 md:px-10 py-8 md:py-12 max-w-6xl">
    <div className="flex flex-wrap items-center justify-between gap-4 mb-6"><h1 className="font-serif text-2xl font-medium text-[#1a3325]">Therapist Management</h1><button onClick={() => setShowAdd(!showAdd)} className="text-[14px] font-bold bg-[#1a3325] text-white px-5 py-2.5 rounded-md">Add Therapist</button></div>
    {showAdd && <form onSubmit={create} className="bg-white border border-[#e5e0d6] rounded-xl p-6 grid md:grid-cols-2 gap-4 mb-8"><h2 className="md:col-span-2 font-medium text-[#1a3325]">Create Therapist Account</h2><input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} placeholder="Full name" className="px-4 py-3 border rounded-lg border-[#ddd9cf]" /><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Email" className="px-4 py-3 border rounded-lg border-[#ddd9cf]" /><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="Phone" className="px-4 py-3 border rounded-lg border-[#ddd9cf]" /><input value={form.professionalTitle} onChange={e => setForm({ ...form, professionalTitle: e.target.value })} placeholder="Professional title / credentials" className="px-4 py-3 border rounded-lg border-[#ddd9cf]" /><input value={form.specialty} onChange={e => setForm({ ...form, specialty: e.target.value })} placeholder="Specialty" className="px-4 py-3 border rounded-lg border-[#ddd9cf]" /><p className="text-sm text-[#5a554d] self-center">The therapist will receive an activation invitation to choose their own password.</p><textarea value={form.bio} onChange={e => setForm({ ...form, bio: e.target.value })} placeholder="Professional biography" className="md:col-span-2 px-4 py-3 border rounded-lg border-[#ddd9cf] h-24" />{formError && <p className="md:col-span-2 text-sm text-red-600">{formError}</p>}<div className="md:col-span-2 flex gap-3"><button disabled={saving} className="bg-[#1a3325] text-white font-bold py-2.5 px-5 rounded-md disabled:opacity-50">{saving ? "Creating…" : "Create Therapist"}</button><button type="button" onClick={() => setShowAdd(false)} className="text-sm text-[#5a554d]">Cancel</button></div></form>}
    {invitation && <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 mb-6 text-sm"><p className="font-medium text-[#1a3325]">Therapist account created. Activation is required before sign-in.</p><p className="text-[#5a554d] mt-1">Invitation email delivery is not configured.</p>{invitation.activationUrl ? <p className="mt-3 break-all"><a href={invitation.activationUrl} target="_blank" rel="noreferrer" className="font-bold text-[#1a3325] underline">Open development activation link</a></p> : <p className="mt-2 text-[#8a7e6a]">Activation URLs are available only when SHOW_INVITATION_URLS is enabled in explicit development/demo mode.</p>}</div>}
    <div className="grid md:grid-cols-2 gap-3 mb-6"><input value={search} onChange={e => { setPage(1); setSearch(e.target.value); }} placeholder="Search name, email, specialty…" className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]" /><select value={active} onChange={e => { setPage(1); setActive(e.target.value); }} className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div>
    {loading ? <p className="text-[#8a7e6a]">Loading…</p> : <div className="bg-white border border-[#e5e0d6] rounded-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#f8f6f2] border-b border-[#e5e0d6] text-left"><tr><th className="px-5 py-3">Therapist</th><th className="px-5 py-3">Specialty</th><th className="px-5 py-3">Clients</th><th className="px-5 py-3">Upcoming</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-[#eceae6]">{therapists.map(t => <tr key={t.id}><td className="px-5 py-3"><p className="font-medium text-[#1a3325]">{t.fullName}</p><p className="text-xs text-[#8a7e6a]">{t.email}</p></td><td className="px-5 py-3 text-[#5a554d]">{t.specialty || "—"}</td><td className="px-5 py-3">{t.clientCount}</td><td className="px-5 py-3">{t.upcomingAppointments}</td><td className="px-5 py-3"><span className={`text-xs font-bold uppercase px-2 py-1 rounded-full ${t.active ? "bg-green-50 text-green-700" : "bg-red-50 text-red-600"}`}>{t.active ? "Active" : "Inactive"}</span></td><td className="px-5 py-3"><Link href={`/admin/therapists/${t.id}`} className="text-xs font-bold text-[#1a3325] hover:underline">Manage</Link></td></tr>)}</tbody></table></div></div>}
    <div className="mt-5 flex items-center justify-between text-sm text-[#5a554d]"><span>{total} therapists</span><div className="flex gap-3"><button disabled={page<=1} onClick={() => setPage(page-1)} className="disabled:opacity-40">Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={() => setPage(page+1)} className="disabled:opacity-40">Next</button></div></div>
  </div>;
}
