"use client";
import { useEffect, useState } from "react";
import { usePortal } from "@/lib/usePortal";

export default function AdminDocuments() {
  const { data, loading: authLoading } = usePortal("admin");
  const [documents, setDocuments] = useState<any[]>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const limit=20;
  useEffect(() => { if(!data) return; const p=new URLSearchParams({page:String(page),limit:String(limit)}); if(search)p.set("search",search);if(category)p.set("category",category);fetch(`/api/admin/documents?${p}`).then(r=>r.json()).then(d=>{setDocuments(d.documents||[]);setTotal(d.total||0);setLoading(false)}).catch(()=>setLoading(false)); },[data,search,category,page]);
  if(authLoading)return <div className="p-8 text-[#8a7e6a]">Loading…</div>;
  const pages=Math.max(1,Math.ceil(total/limit));
  return <div className="px-6 md:px-10 py-8 md:py-12 max-w-6xl"><h1 className="font-serif text-2xl font-medium text-[#1a3325] mb-3">Document Management</h1><p className="text-sm text-[#5a554d] mb-6">Administrative metadata only. Private clinical file contents remain restricted to the authorized care team.</p><div className="grid md:grid-cols-2 gap-3 mb-6"><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="Search filename or client…" className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/><select value={category} onChange={e=>{setPage(1);setCategory(e.target.value)}} className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"><option value="">All categories</option><option value="general">General</option><option value="forms">Forms</option><option value="reports">Reports</option><option value="other">Other</option></select></div>{loading?<p className="text-[#8a7e6a]">Loading…</p>:<div className="bg-white border border-[#e5e0d6] rounded-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#f8f6f2] border-b border-[#e5e0d6] text-left"><tr><th className="px-5 py-3">File</th><th className="px-5 py-3">Client</th><th className="px-5 py-3">Therapist</th><th className="px-5 py-3">Uploaded By</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Size</th></tr></thead><tbody className="divide-y divide-[#eceae6]">{documents.map(d=><tr key={d.id}><td className="px-5 py-3"><p className="font-medium text-[#1a3325]">{d.fileName}</p><p className="text-xs text-[#8a7e6a]">{d.mimeType}</p></td><td className="px-5 py-3 text-[#5a554d]">{d.clientName}</td><td className="px-5 py-3 text-[#5a554d]">{d.therapistName||"—"}</td><td className="px-5 py-3 text-[#5a554d]">{d.uploadedByName||"—"}</td><td className="px-5 py-3 text-[#5a554d] capitalize">{d.category}</td><td className="px-5 py-3 text-[#5a554d]">{(Number(d.fileSize)/1024).toFixed(0)} KB</td></tr>)}</tbody></table></div></div>}<div className="mt-5 flex justify-between text-sm text-[#5a554d]"><span>{total} documents</span><div className="flex gap-3"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="disabled:opacity-40">Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)} className="disabled:opacity-40">Next</button></div></div></div>;
}
