"use client";
import { useEffect, useState } from "react";
import { usePortal } from "@/lib/usePortal";

export default function AdminSettings() {
  const { data, loading: authLoading } = usePortal("admin");
  const [settings,setSettings]=useState<any>(null);const [loading,setLoading]=useState(true);const [form,setForm]=useState({name:"",email:"",phone:"",address:"",currency:"KES",timezone:"Africa/Nairobi"});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{if(!data)return;fetch("/api/portal/settings").then(r=>r.json()).then(d=>{setSettings(d.settings);if(d.settings)setForm({name:d.settings.name||"",email:d.settings.email||"",phone:d.settings.phone||"",address:d.settings.address||"",currency:d.settings.currency||"KES",timezone:d.settings.timezone||"Africa/Nairobi"});setLoading(false)}).catch(()=>setLoading(false));},[data]);
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");const r=await fetch("/api/portal/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setSaving(false);setMessage(r.ok?"Settings updated.":d.error||"Unable to save settings.");}
  if(authLoading||loading)return <div className="p-8 text-[#8a7e6a]">Loading…</div>;
  return <div className="px-6 md:px-10 py-8 md:py-12 max-w-xl"><h1 className="font-serif text-2xl font-medium text-[#1a3325] mb-8">Practice Settings</h1><form onSubmit={save} className="space-y-5"><div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Practice Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/></div><div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/></div><div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Phone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="w-full px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/></div><div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Address</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="w-full px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Currency</label><input value="KES" disabled className="w-full px-4 py-3 rounded-lg bg-[#eceae6] border border-[#ddd9cf] text-[#5a554d]"/></div><div><label className="block text-xs font-bold uppercase tracking-wider text-[#8a7e6a] mb-2">Practice Timezone</label><input value="Africa/Nairobi" disabled className="w-full px-4 py-3 rounded-lg bg-[#eceae6] border border-[#ddd9cf] text-[#5a554d]"/></div></div><p className="text-xs text-[#8a7e6a]">Timezone is locked to preserve existing appointment times.</p><button disabled={saving} className="bg-[#1a3325] text-white font-bold py-3 px-6 rounded-md hover:bg-[#143025] disabled:opacity-50">{saving?"Saving…":"Save Settings"}</button>{message&&<p className={`text-sm ${message==='Settings updated.'?'text-green-700':'text-red-600'}`}>{message}</p>}</form></div>;
}
