"use client";
import Link from "next/link";
import { use, useCallback, useEffect, useState } from "react";
import { usePortal } from "@/lib/usePortal";
import { ArrowLeft, CalendarPlus, FileText, MessageSquare, Plus, Save } from "lucide-react";

type Tab = "overview" | "appointments" | "notes" | "documents" | "messages";

export default function TherapistClientWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const { id: clientId } = use(params);
  const { data: portal, loading: authLoading } = usePortal("therapist");
  const [record, setRecord] = useState<any>(null); const [notes, setNotes] = useState<any[]>([]);
  const [notesPage, setNotesPage] = useState(1); const [notesTotal, setNotesTotal] = useState(0);
  const [tab, setTab] = useState<Tab>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [noteContent, setNoteContent] = useState(""); const [noteAppointmentId, setNoteAppointmentId] = useState(""); const [editingNote, setEditingNote] = useState<any>(null); const [savingNote, setSavingNote] = useState(false); const [noteError, setNoteError] = useState("");
  const [services, setServices] = useState<any[]>([]); const [scheduleOpen, setScheduleOpen] = useState(false); const [scheduleService, setScheduleService] = useState(""); const [scheduleDate, setScheduleDate] = useState(""); const [slots, setSlots] = useState<any[]>([]); const [scheduleSlot, setScheduleSlot] = useState<any>(null); const [scheduling, setScheduling] = useState(false); const [scheduleError, setScheduleError] = useState("");

  const loadWorkspace = useCallback(async () => {
    if (!portal) return;
    setLoading(true); setError("");
    try {
      const response = await fetch(`/api/portal/therapist/clients/${clientId}`, { cache: "no-store" }); const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Unable to load client."); setRecord(payload);
    } catch (e: any) { setError(e.message || "Unable to load client."); } finally { setLoading(false); }
  }, [portal, clientId]);

  const loadNotes = useCallback(async (targetPage = 1, append = false) => {
    if (!portal) return;
    const response = await fetch(`/api/portal/therapist/clients/${clientId}/notes?page=${targetPage}&limit=10`, { cache: "no-store" }); const payload = await response.json();
    if (!response.ok) { setNoteError(payload.error || "Unable to load notes."); return; }
    setNotes((current) => append ? [...current, ...(payload.notes || [])] : (payload.notes || [])); setNotesPage(payload.page || targetPage); setNotesTotal(payload.total || 0);
  }, [portal, clientId]);

  useEffect(() => { if (portal) { loadWorkspace(); loadNotes(); fetch("/api/public/services").then(r => r.json()).then(d => setServices(d.services || [])); } }, [portal, loadWorkspace, loadNotes]);
  useEffect(() => {
    if (!portal?.therapistId || !scheduleService || !scheduleDate) { setSlots([]); setScheduleSlot(null); return; }
    setScheduleError(""); setScheduleSlot(null);
    fetch(`/api/public/availability?therapistId=${portal.therapistId}&serviceId=${scheduleService}&date=${scheduleDate}`).then(r => r.json()).then(d => { setSlots(d.slots || []); if (d.error || d.message) setScheduleError(d.error || d.message); }).catch(() => setScheduleError("Unable to load available times."));
  }, [portal?.therapistId, scheduleService, scheduleDate]);

  async function saveNote(e: React.FormEvent) {
    e.preventDefault(); const content = noteContent.trim(); if (!content) { setNoteError("Note content is required."); return; }
    setSavingNote(true); setNoteError("");
    try {
      const response = editingNote
        ? await fetch(`/api/portal/therapist/session-notes/${editingNote.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) })
        : await fetch(`/api/portal/therapist/clients/${clientId}/notes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content, appointmentId: noteAppointmentId || null }) });
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to save session note.");
      setNoteContent(""); setNoteAppointmentId(""); setEditingNote(null); await loadNotes(notesPage); await loadWorkspace();
    } catch (e: any) { setNoteError(e.message || "Unable to save session note."); } finally { setSavingNote(false); }
  }

  async function scheduleSession(e: React.FormEvent) {
    e.preventDefault(); if (!scheduleService || !scheduleDate || !scheduleSlot) { setScheduleError("Select a service, date, and available time."); return; }
    setScheduling(true); setScheduleError("");
    try {
      const response = await fetch("/api/portal/appointments/book", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clientId, serviceId: scheduleService, date: scheduleDate, startTime: scheduleSlot.startTime }) });
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to schedule session.");
      setScheduleOpen(false); setScheduleService(""); setScheduleDate(""); setScheduleSlot(null); setSlots([]); await loadWorkspace();
    } catch (e: any) { setScheduleError(e.message || "Unable to schedule session."); } finally { setScheduling(false); }
  }

  if (authLoading || loading) return <div className="p-8 text-[#8a7e6a]">Loading client workspace…</div>;
  if (error || !record?.client) return <div className="p-8"><p className="text-red-600">{error || "Client not found or not authorized."}</p><Link href="/therapist/clients" className="text-[#1a3325] underline mt-4 inline-block">Back to Clients</Link></div>;
  const { client, appointments = [], documents = [], activity = [] } = record;
  const upcoming = appointments.filter((a: any) => !["cancelled", "completed", "no-show"].includes(a.status));
  const past = appointments.filter((a: any) => ["completed", "no-show"].includes(a.status) || (a.status === "cancelled"));
  const tabs: { id: Tab; label: string }[] = [{ id: "overview", label: "Overview" }, { id: "appointments", label: "Appointments" }, { id: "notes", label: "Session Notes" }, { id: "documents", label: "Documents" }, { id: "messages", label: "Messages" }];

  return <div className="px-6 md:px-10 py-8 md:py-12 max-w-6xl">
    <Link href="/therapist/clients" className="inline-flex items-center gap-2 text-[14px] text-[#8a7e6a] hover:text-[#1a3325] transition mb-6"><ArrowLeft size={16} /> Back to Clients</Link>
    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-5 mb-7"><div><h1 className="font-serif text-2xl font-medium text-[#1a3325] mb-1">{client.fullName}</h1><p className="text-sm text-[#5a554d]">{client.email}{client.phone ? ` · ${client.phone}` : ""}</p><div className="flex gap-2 mt-3"><span className={`text-xs font-bold uppercase px-2 py-1 rounded-full ${client.active ? "bg-green-50 text-green-700" : "bg-red-50 text-red-600"}`}>{client.active ? "Active" : "Inactive"}</span>{!client.verified && <span className="text-xs font-bold uppercase px-2 py-1 rounded-full bg-amber-50 text-amber-700">Activation Pending</span>}</div></div><div className="flex flex-wrap gap-3"><button onClick={() => setScheduleOpen(!scheduleOpen)} className="inline-flex items-center gap-2 text-[14px] font-bold bg-[#1a3325] text-white px-5 py-2.5 rounded-md hover:bg-[#143025] transition"><CalendarPlus size={16}/> Schedule Session</button><button onClick={() => { setTab("notes"); setEditingNote(null); setNoteContent(""); }} className="inline-flex items-center gap-2 text-[14px] font-medium border border-[#ddd8cf] text-[#1a3325] px-5 py-2.5 rounded-md"><Plus size={16}/> Add Session Note</button></div></div>
    {scheduleOpen && <form onSubmit={scheduleSession} className="bg-white border border-[#e5e0d6] rounded-xl p-6 mb-7 grid md:grid-cols-3 gap-4"><h2 className="md:col-span-3 font-medium text-[#1a3325]">Schedule Session for {client.fullName}</h2><select required value={scheduleService} onChange={(e) => setScheduleService(e.target.value)} className="px-4 py-3 border rounded-lg border-[#ddd9cf]"><option value="">Select service…</option>{services.map((service: any) => <option key={service.id} value={service.id}>{service.name} · {service.durationMinutes} min</option>)}</select><input type="date" required value={scheduleDate} onChange={(e) => setScheduleDate(e.target.value)} className="px-4 py-3 border rounded-lg border-[#ddd9cf]"/><select required value={scheduleSlot?.startTime || ""} onChange={(e) => setScheduleSlot(slots.find((slot) => slot.startTime === e.target.value) || null)} className="px-4 py-3 border rounded-lg border-[#ddd9cf]"><option value="">Select available time…</option>{slots.map((slot) => <option key={slot.startTime} value={slot.startTime}>{slot.startTime} – {slot.endTime}</option>)}</select>{scheduleError && <p className="md:col-span-3 text-sm text-red-600">{scheduleError}</p>}<div className="md:col-span-3 flex gap-3"><button disabled={scheduling} className="bg-[#1a3325] text-white font-bold py-2.5 px-5 rounded-md disabled:opacity-50">{scheduling ? "Scheduling…" : "Schedule Session"}</button><button type="button" onClick={() => setScheduleOpen(false)} className="text-sm text-[#5a554d]">Cancel</button></div></form>}
    <div className="border-b border-[#e5e0d6] mb-7 overflow-x-auto"><div className="flex gap-5 min-w-max">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`pb-3 text-sm font-medium border-b-2 transition ${tab === item.id ? "border-[#1a3325] text-[#1a3325]" : "border-transparent text-[#8a7e6a]"}`}>{item.label}</button>)}</div></div>
    {tab === "overview" && <div className="grid lg:grid-cols-3 gap-6"><section className="lg:col-span-2 bg-white border border-[#e5e0d6] rounded-xl p-6"><h2 className="font-medium text-[#1a3325] mb-4">Client Overview</h2><div className="grid sm:grid-cols-3 gap-4 text-sm"><div><p className="text-[#8a7e6a]">Next appointment</p><p className="font-medium text-[#1a3325] mt-1">{upcoming[0] ? `${upcoming[0].date} · ${upcoming[0].startTime}` : "None scheduled"}</p></div><div><p className="text-[#8a7e6a]">Previous appointment</p><p className="font-medium text-[#1a3325] mt-1">{past[0] ? `${past[0].date} · ${past[0].status}` : "None"}</p></div><div><p className="text-[#8a7e6a]">Appointments</p><p className="font-medium text-[#1a3325] mt-1">{client.appointmentCount}</p></div><div><p className="text-[#8a7e6a]">Documents</p><p className="font-medium text-[#1a3325] mt-1">{client.documentCount}</p></div><div><p className="text-[#8a7e6a]">Unread messages</p><p className="font-medium text-[#1a3325] mt-1">{client.unreadMessages}</p></div><div><p className="text-[#8a7e6a]">Client since</p><p className="font-medium text-[#1a3325] mt-1">{new Date(client.createdAt).toLocaleDateString("en-KE")}</p></div></div></section><section className="bg-white border border-[#e5e0d6] rounded-xl p-6"><h2 className="font-medium text-[#1a3325] mb-4">Quick Actions</h2><div className="space-y-3 text-sm"><button onClick={() => setScheduleOpen(true)} className="block text-[#1a3325] font-bold hover:underline">Schedule session</button><Link href={`/therapist/messages?clientId=${clientId}`} className="block text-[#1a3325] font-bold hover:underline">Open messages</Link><Link href={`/therapist/documents?clientId=${clientId}`} className="block text-[#1a3325] font-bold hover:underline">View documents</Link><button onClick={() => setTab("notes")} className="block text-[#1a3325] font-bold hover:underline">Add session note</button></div></section><section className="lg:col-span-3 bg-white border border-[#e5e0d6] rounded-xl p-6"><h2 className="font-medium text-[#1a3325] mb-4">Recent Activity</h2>{activity.length ? <div className="space-y-2 text-sm">{activity.map((event: any, index: number) => <div key={`${event.type}-${index}`} className="flex justify-between border-b border-[#eceae6] pb-2"><span className="capitalize text-[#3d3830]">{event.type}: {event.label}</span><span className="text-[#8a7e6a]">{new Date(event.createdAt).toLocaleString("en-KE", { dateStyle: "short", timeStyle: "short" })}</span></div>)}</div> : <p className="text-sm text-[#5a554d]">No recent activity.</p>}</section></div>}
    {tab === "appointments" && <section><h2 className="font-medium text-[#1a3325] mb-4">Appointment History</h2>{appointments.length ? <div className="space-y-3">{appointments.map((appointment: any) => <div key={appointment.id} className="bg-white border border-[#e5e0d6] rounded-xl p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="font-medium text-[#1a3325]">{appointment.date} · {appointment.startTime}–{appointment.endTime}</p><p className="text-sm text-[#5a554d]">{appointment.serviceName || "Session"}</p></div><div className="flex gap-2"><span className="text-xs font-bold uppercase px-2 py-1 rounded-full bg-[#eceae6] text-[#5a554d]">{appointment.status}</span><span className="text-xs font-bold uppercase px-2 py-1 rounded-full bg-[#eceae6] text-[#5a554d]">{appointment.paymentStatus}</span></div></div>)}</div> : <p className="text-sm text-[#5a554d]">No appointments found.</p>}</section>}
    {tab === "notes" && <section className="max-w-3xl"><form onSubmit={saveNote} className="bg-white border border-[#e5e0d6] rounded-xl p-6 mb-6"><h2 className="font-medium text-[#1a3325] mb-4">{editingNote ? "Edit Session Note" : "Add Session Note"}</h2><select value={noteAppointmentId} onChange={(e) => setNoteAppointmentId(e.target.value)} disabled={Boolean(editingNote)} className="w-full px-4 py-3 rounded-lg border border-[#ddd9cf] mb-4"><option value="">General client note (no appointment)</option>{appointments.map((appointment: any) => <option key={appointment.id} value={appointment.id}>{appointment.date} · {appointment.startTime} · {appointment.serviceName || "Session"}</option>)}</select><textarea required maxLength={12000} value={noteContent} onChange={(e) => setNoteContent(e.target.value)} placeholder="Private therapist session note. This is never visible to the client." className="w-full min-h-40 px-4 py-3 rounded-lg border border-[#ddd9cf] whitespace-pre-wrap" />{noteError && <p className="text-sm text-red-600 mt-3">{noteError}</p>}<div className="flex gap-3 mt-4"><button disabled={savingNote} className="inline-flex items-center gap-2 bg-[#1a3325] text-white font-bold py-2.5 px-5 rounded-md disabled:opacity-50"><Save size={15}/>{savingNote ? "Saving…" : editingNote ? "Save Changes" : "Save Note"}</button>{editingNote && <button type="button" onClick={() => { setEditingNote(null); setNoteContent(""); setNoteAppointmentId(""); }} className="text-sm text-[#5a554d]">Cancel Edit</button>}</div></form><h2 className="font-medium text-[#1a3325] mb-4">Private Session Notes</h2>{notes.length ? <div className="space-y-4">{notes.map((note: any) => <article key={note.id} className="bg-white border border-[#e5e0d6] rounded-xl p-5"><div className="flex justify-between gap-3 mb-3"><div><p className="text-xs text-[#8a7e6a]">{note.appointmentDate ? `${note.appointmentDate} · ${note.appointmentStartTime}` : "General note"}</p><p className="text-xs text-[#8a7e6a]">Created {new Date(note.createdAt).toLocaleString("en-KE", { dateStyle: "short", timeStyle: "short" })}{note.updatedAt !== note.createdAt ? " · Edited" : ""}</p></div><button onClick={() => { setEditingNote(note); setNoteContent(note.content); setNoteAppointmentId(note.appointmentId || ""); }} className="text-xs font-bold text-[#1a3325] hover:underline">Edit</button></div><p className="text-sm text-[#2a2724] whitespace-pre-wrap break-words">{note.content}</p></article>)}</div> : <p className="text-sm text-[#5a554d]">No private session notes yet.</p>}{notesTotal > notes.length && <div className="mt-5 text-center"><button onClick={() => loadNotes(notesPage + 1, true)} className="text-sm font-bold text-[#1a3325] underline">Load older notes</button></div>}</section>}
    {tab === "documents" && <section><div className="flex items-center justify-between mb-4"><h2 className="font-medium text-[#1a3325]">Recent Documents</h2><Link href={`/therapist/documents?clientId=${clientId}`} className="text-sm font-bold text-[#1a3325] hover:underline">Open documents</Link></div>{documents.length ? <div className="space-y-3">{documents.map((document: any) => <div key={document.id} className="bg-white border border-[#e5e0d6] rounded-xl p-4 flex justify-between gap-3"><div><p className="font-medium text-[#1a3325]">{document.fileName}</p><p className="text-xs text-[#8a7e6a]">{document.category} · {document.uploadedByName || "Unknown"} · {Math.ceil(Number(document.fileSize) / 1024)} KB</p></div></div>)}</div> : <p className="text-sm text-[#5a554d]">No documents exchanged yet.</p>}</section>}
    {tab === "messages" && <section className="bg-white border border-[#e5e0d6] rounded-xl p-6 max-w-xl"><MessageSquare size={20} className="text-[#1a3325] mb-3"/><h2 className="font-medium text-[#1a3325] mb-2">Private Messages</h2><p className="text-sm text-[#5a554d] mb-4">Open the existing private messaging workspace to communicate with {client.fullName}. Current care-team authorization is enforced by the server.</p><Link href={`/therapist/messages?clientId=${clientId}`} className="text-sm font-bold text-[#1a3325] hover:underline">Open messages</Link></section>}
  </div>;
}
