"use client";
import { useEffect, useState } from "react";
import { usePortal } from "@/lib/usePortal";

export default function AdminPayments() {
  const { data, loading: authLoading }=usePortal("admin");const [payments,setPayments]=useState<any[]>([]);const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const limit=20;
  useEffect(()=>{if(!data)return;const p=new URLSearchParams({page:String(page),limit:String(limit)});if(search)p.set("search",search);if(status)p.set("status",status);if(from)p.set("from",from);if(to)p.set("to",to);fetch(`/api/admin/payments?${p}`).then(r=>r.json()).then(d=>{setPayments(d.payments||[]);setTotal(d.total||0);setLoading(false)}).catch(()=>setLoading(false));},[data,search,status,from,to,page]);
  if(authLoading)return <div className="p-8 text-[#8a7e6a]">Loading…</div>;const pages=Math.max(1,Math.ceil(total/limit));
  return <div className="px-6 md:px-10 py-8 md:py-12 max-w-7xl"><h1 className="font-serif text-2xl font-medium text-[#1a3325] mb-6">Payments</h1><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mb-6"><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="Client or transaction reference…" className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/><select value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}} className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"><option value="">All statuses</option>{['pending','successful','failed','refunded'].map(v=><option key={v} value={v}>{v}</option>)}</select><input type="date" value={from} onChange={e=>{setPage(1);setFrom(e.target.value)}} className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/><input type="date" value={to} onChange={e=>{setPage(1);setTo(e.target.value)}} className="px-4 py-3 rounded-lg bg-white border border-[#ddd9cf]"/></div>{loading?<p className="text-[#8a7e6a]">Loading…</p>:<div className="bg-white border border-[#e5e0d6] rounded-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#f8f6f2] border-b border-[#e5e0d6] text-left"><tr><th className="px-5 py-3">Client</th><th className="px-5 py-3">Session</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Provider / Method</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Reference</th></tr></thead><tbody className="divide-y divide-[#eceae6]">{payments.map(p=><tr key={p.id}><td className="px-5 py-3 text-[#1a3325]">{p.clientName}</td><td className="px-5 py-3 text-[#5a554d]">{p.serviceName||'—'}<br/>{p.appointmentDate||'—'}</td><td className="px-5 py-3 font-medium">{p.currency||'KES'} {Number(p.amountKES).toLocaleString()}</td><td className="px-5 py-3 text-[#5a554d]">{p.provider}{p.method?` · ${p.method}`:''}</td><td className="px-5 py-3"><span className={`text-xs font-bold uppercase px-2 py-1 rounded-full ${p.status==='successful'?'bg-green-50 text-green-700':p.status==='failed'?'bg-red-50 text-red-600':'bg-amber-50 text-amber-700'}`}>{p.status}</span></td><td className="px-5 py-3 text-xs text-[#8a7e6a]">{p.transactionRef}</td></tr>)}</tbody></table></div></div>}<div className="mt-5 flex justify-between text-sm text-[#5a554d]"><span>{total} payments</span><div className="flex gap-3"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="disabled:opacity-40">Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)} className="disabled:opacity-40">Next</button></div></div></div>;
}
